### ISSUE TITLE
Cannot be marked as external

### ISSUE THREAD

**Issue by theIYD** [kazijawad/esbuild-plugin-svgr#14]
I am trying to use this plugin for SVGs used as ReactComponent with ESBuild.

I am facing `The entry point "./src/assets/text.svg" cannot be marked as external` error. 

Can someone help me resolve this ?

My config: 
```
export default defineConfig({
	entry: entryPoints,
	sourcemap: false,
	clean: true,
	dts: false,
	external: ["react", "react-proptypes", "~video.js/dist/video-js.min.css"],
	esbuildPlugins: [
		svgr({
			exportType: "named"
		}),
		{
			name: lessLoader().name,
			setup: lessLoader().setup as any
		}
	]
});
```

**Comment by patrick-lienau** [comment]
@theIYD I just PR'd (#19) my fix for this. Not sure if this is still relevant to you... 🤷‍♂️ Until that PR is merged, you can use the scoped version of this package that I published to NPM.
```
npm install -D @patrick-lienau/esbuild-plugin-svgr
```
or
```sh
yarn add -D @patrick-lienau/esbuild-plugin-svgr
```

you do need to pass a `markExternal: false` parameter to the plugin constructor like so:
```ts
await esbuild.build({
    // ...
     plugins: [
         svgrPlugin({ markExternal: false })
     ]
});
```

**Comment by kazijawad** [comment]
This is now fixed with @patrick-lienau's changes in esbuild-plugin-svgr@3.1.0
