### ISSUE TITLE
pass filePath to svgr

### ISSUE THREAD

**Issue by Hadarder** [kazijawad/esbuild-plugin-svgr#5]
i want to use esbuild-plugin-svgr with @svgr/plugin-svgo.
svgo has prefixIds plugin which sets all the ids attributes to the SVG file name. 
Since esbuild-plugin-svgr  doesn't pass svgr the filePath, svgo is changing all the ids (of different svgs) to the same id which causing problems.

I've created a pr with a solution #4

**Comment by kazijawad** [comment]
PR #4 has been merged and is live in version `0.0.3`, thank you!
